### ISSUE TITLE
Add a way to specify the OTP app to collect version from

### ISSUE THREAD

**Issue by zacharydenton** [appcues/exsentry#6]
It would be great if there was a way to specify which app to send version info for. Right now, since [ExSentry.Utils.version](https://github.com/appcues/exsentry/blob/master/lib/exsentry/utils.ex#L11) defaults to `:exsentry`, the Plug will just send ExSentry's version number to Sentry.

**Comment by ASCrookes** [comment]
+1

**Comment by gamache** [comment]
Sorry for letting this one sit for so long!  This is fixed in 0.7.1.
